### ISSUE TITLE
RFC0009 - HTTP-statuscodes

### ISSUE THREAD

**Issue by dennisdegouw** [iStandaarden/iWlz-RFC#12]
Status: Vervallen

Link naar [RFC0009](https://github.com/iStandaarden/iWlz-RFC/blob/main/RFC/RFC0009%20-%20HTTP-statuscodes.md)

**Comment by rvanrest** [comment]
Besloten is om geen generieke HTTP-statuscodes te definiëren maar deze situationeel te maken. 

Wanneer nodig zijn HTTP-statuscodes onderdeel van een specifieke RFC
