### ISSUE TITLE
RFC0016 - Service directory

### ISSUE THREAD

**Issue by dennisdegouw** [iStandaarden/iWlz-RFC#20]
### Link naar RFC

**Link naar [RFC0016 - Service Directory](https://github.com/iStandaarden/iWlz-RFC/blob/main/RFC/RFC0016%20-%20Service%20directory.md)**

### Onderwerp

Functionele beschrijving van de werking van de **service directory**

### RFC heeft impact op

- [ ] Indicatieregister
- [ ] Bemiddelingsregister - Centraal
- [ ] Bemiddelingsregister - Decentraal
- [ ] CIZ back-office
- [ ] CIZ Netwerkadapter
- [ ] nID
- [ ] Silvester
- [ ] Raadplegers / GraphQL
- [ ] anders, (geef hieronder aan)

### Selecteer in de kolom rechts het project "RFC-netwerkmodel"

- [X] done

**Comment by rvanrest** [comment]
Voorstel om Service Directory te hernoemen naar Diensten catalogus omdat dit de lading beter dekt en de term Service Directory ook voor Adresboek wordt gebruikt

**Comment by rvanrest** [comment]
Voorstel team Realisatie: laten vervallen. RFC is gesplitst naar losse onderdelen
- [#4] - Adresboek
- [#29] - Dienstencatalogus
