### ISSUE TITLE
RFC0013 - Identiteit

### ISSUE THREAD

**Issue by dennisdegouw** [iStandaarden/iWlz-RFC#8]
Dit document is een duplicaat van [RFC0015](https://github.com/iStandaarden/iWlz-RFC/blob/main/RFC/RFC0015%20-%20Identiteit.md) getiteld "Identiteit". Lezers wordt aangeraden om RFC0015 te raadplegen voor de meest actuele informatie.

Link naar [RFC0013](https://github.com/iStandaarden/iWlz-RFC/blob/main/RFC/RFC0013%20-%20Identiteit%20%5Bduplicaat%20RFC0015%5D.md)

**Comment by rvanrest** [comment]
Duplicate van RFC0015 zie ook [#10]
